Cloud Apps/Bikefy-Web/Controllers/DocksController.cs
using CityCycles.Composite.BusMessages.Management;
using CityCycles.Composite.Data.ManagementData;
using CityCycles.Composite.Model.Bike;
using CityCycles.Composite.Model.Dock;
using CityCycles.Web.Providers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using NServiceBus;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CityCycles.Web.Controllers
{
    [Route("[controller]/[action]")]
    public class DocksController : Controller
    {
        public static class LogEvents
        {
            public static readonly EventId OnBoardingDock = new EventId(1, nameof(OnBoardPost));
            public static readonly EventId UpdatingDock = new EventId(2, nameof(Update));
        }

        private readonly IServiceProvider _serviceProvider;

        private IApiProvider _apiProvider;
        private IEndpointInstance _endpointInstance;

        private ILogger _logger;

        public DocksController(IServiceProvider provider)
        {
            _apiProvider = provider.GetService<IApiProvider>();
            _endpointInstance = provider.GetService<IEndpointInstance>();

            _logger = provider.GetService<ILogger<DocksController>>();
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var json = await _apiProvider.SendGetRequest(_apiProvider.BuildUrl("Dock", "FindAll"));

            var docks = JsonConvert.DeserializeObject<List<DockStatus>>(json);


            return View(docks);
        }


        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Locations()
        {
            var url = _apiProvider.BuildUrl("Dock", "FindAll");

            // Send the request
            var result = await _apiProvider.SendGetRequest(url);

            var model = JsonConvert.DeserializeObject<List<DockStatus>>(result);

            return View(model);
        }

        [HttpGet]
        //[Authorize(Roles = CityCyclesRoles.CityCyclesDocks)]
        public IActionResult OnBoard()
        {
            return View();
        }

        [HttpPost, ActionName("OnBoard")]
        [ValidateAntiForgeryToken]
        //Authorize(Roles = CityCyclesRoles.CityCyclesDocks)
        public async Task<IActionResult> OnBoardPost(DockRequest request)
        {
            // Model is not valid
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var url = _apiProvider.BuildUrl("Dock", "CreateNew");

            try
            {
                // Send the request
                var result = await _apiProvider.SendPostRequest(url, request);

                var dict = JsonConvert.DeserializeObject<Dictionary<string, string>>(result);

                // Generate a random string of length 32 to be used as the password to the dock.
                var p = RandomString(32);

                // Request Api to create a dock account
                await _endpointInstance.Send(new CreateDockAccount()
                {
                    DockId = Guid.Parse(dict["dockId"]),
                    DockName = request.Name,
                    Password = p
                });

                // Set view data to contain the password 
                ViewData["hasPassword"] = true;
                ViewData["dockId"] = dict["dockId"];
                ViewData["DockPassword"] = p;

                return View();
            }
            catch (WebException e)
            {
                _logger.LogWarning(LogEvents.OnBoardingDock, e, "Could not get a dock");

                ViewBag.CustomError = true;
                //Display the error
                ModelState.AddModelError("Custom-Error", e.Message);

                return View(request);
            }
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Update([FromRoute(Name = "id")]Guid dockId)
        {
            // Validate dock id
            if (dockId == Guid.Empty)
            {
                return RedirectToAction("Error", "Home");
            }

            var url = _apiProvider.BuildUrl("Dock", $"FindById/{dockId}");

            try
            {
                var dock = JsonConvert.DeserializeObject<Dock>(await _apiProvider.SendGetRequest(url));

                // If dock couldn't be found
                if (dock == null)
                {
                    ModelState.AddModelError("Custom-Error", "Dock with the provided id could not be retrieved");
                    ViewBag.CustomError = true;
                    return View();
                }

                // Split it by the comma
                var locations = dock.Location.Split(" ");

                // Create dock request model and pass it to the view
                var dockRequest = new DockRequest()
                {
                    Id = dock.Id,
                    Name = dock.Name,
                    Capacity = dock.MaximumCapacity,
                    Latitude = decimal.Parse(locations.FirstOrDefault()),
                    Longitude = decimal.Parse(locations.ElementAtOrDefault(1)),
                };

                // Iterate over all the bikes for this dock
                foreach (var bike in dock.Bikes)
                {
                    // Add the current bike to the dock model
                    dockRequest.Bikes.Add(new BikeModel()
                    {
                        BikeId = bike.Id,
                        Status = bike.Status,
                        DockId = bike.DockId,
                        LastUpdate = bike.LastReport
                    });
                }

                return View(dockRequest);
            }
            catch (Exception e)
            {
                // Log error and send user to error page
                _logger.LogError(LogEvents.UpdatingDock, e, "There was an error retriving dock from the api");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(DockRequest request)
        {
            // Validate the model
            if (!ModelState.IsValid)
            {
                return View();
            }

            var url = _apiProvider.BuildUrl("Dock", "Update");

            try
            {
                await _apiProvider.SendPostRequest(url, request);

                return RedirectToAction("Locations");
            }
            catch (WebException e)
            {
                using (_logger.BeginScope(new Dictionary<string, object>
                {
                    ["Dock"] = request.Id
                }))
                {
                    // Log error and send user to error page
                    _logger.LogError(LogEvents.UpdatingDock, e, "There was an error updating the dock.");

                    ModelState.AddModelError("Custom-Error", e.Message);
                    ViewBag.CustomError = true;
                    return View(request);
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid DockId)
        {
            var url = _apiProvider.BuildUrl("Dock", $"Delete/{DockId}");

            try
            {
                await _apiProvider.SendGetRequest(url);

                // Send bus message to delete  dock account
                await _endpointInstance.Send(new DeleteDockAccount()
                {
                    DockId = DockId
                });

                return RedirectToAction("Locations");
            }
            catch (WebException e)
            {
                using (_logger.BeginScope(new Dictionary<string, object>
                {
                    ["Dock"] = DockId
                }))
                {
                    // Log error and send user to error page
                    _logger.LogError(LogEvents.UpdatingDock, e, "There was an error updating the dock.");

                    return RedirectToAction("Error", "Home");
                }
            }
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> AddBike(Guid id)
        {
            BikeRequest req = new BikeRequest
            {
                DockId = id
            };

            //Creation of url for Post request
            string url = _apiProvider.BuildUrl("Bikes", "CreateNew");

            try
            {
                //Send request to api to try for response
                string message = await _apiProvider.SendPostRequest(url, req);

                var apiResult = JsonConvert.DeserializeObject<Dictionary<string, object>>(message);

                using (_logger.BeginScope(apiResult))
                {
                    //_logger.LogInformation(LogEvents.CreateNewBike,
                    //    $"Created new Bike at Dock {model.DockName} successfully with API");
                }

            }
            catch (Exception e)
            {
                //Display the error
                ModelState.AddModelError("Custom-Error", e.Message);

                return RedirectToAction(nameof(Update), new { id = id });
            }

            return RedirectToAction(nameof(Update), new { id = id });
        }

        // GET: api/Bike/Delete
        [HttpGet("{id}")]
        public async Task<IActionResult> DeleteBike([FromQuery(Name = "bike")]Guid bikeId, [FromRoute(Name = "id")]Guid dockId)
        {
            var url = _apiProvider.BuildUrl("Bikes", $"Delete/{bikeId}");

            await _apiProvider.SendGetRequest(url);

            return RedirectToAction(nameof(Update), new { id = dockId });

        }

Cloud Apps/Bikefy-Web/Controllers/HomeController.cs
using System.Diagnostics;
using CityCycles.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CityCycles.Web.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "City Cycles Information";

            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cloud Apps/Bikefy-Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<!-- begin::Portlet-->

<div class="k-portlet">
    <div class="k-portlet__body">
        <h3 class="k-heading k-heading--center k-heading--space-lg k-heading--lg">Who are City Cycles</h3>

        <!--begin::Accordion-->
        <div class="accordion accordion-light" id="accordion-about">
            <div class="card">
                <div class="card-header" id="headingOne1">
                    <div class="card-title collapsed" data-toggle="collapse" role="button" data-target="#collapseOne1" aria-expanded="true" aria-controls="collapseOne1">
                        What have we done?
                    </div>
                </div>
                <div id="collapseOne1" class="collapse" aria-labelledby="headingOne1" data-parent="#accordion-about">
                    <div class="card-body">
                        City Cycles is a bike rental system which allows you to hire a bike for your journey to work/Uni/school or for a leisurely cycle.
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" id="headingTwo1">
                    <div class="card-title collapsed" data-toggle="collapse" role="button" data-target="#collapseTwo1" aria-expanded="false" aria-controls="collapseTwo1">
                        How do we operate?
                    </div>
                </div>
                <div id="collapseTwo1" class="collapse" aria-labelledby="headingTwo1" data-parent="#accordion-about">
                    <div class="card-body">
                        You can either register beforehand and pre-book a bike for your trip or you may visit your local City Cycles bike dock and hire an available bike there.<br />
                        Rates are charged hourly and the money will be taken out of your account once the bike has been returned.
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" id="headingThree1">
                    <div class="card-title collapsed" data-toggle="collapse" role="button" data-target="#collapseThree1" aria-expanded="false" aria-controls="collapseThree1">
                        Where can you find us?
                    </div>
                </div>
                <div id="collapseThree1" class="collapse" aria-labelledby="headingThree1" data-parent="#accordion-about" style="">
                    <div class="card-body">
                        <a class="btn btn-link" asp-controller="Docks" asp-action="Locations"> Click here to view dock locations</a>
                    </div>
                </div>
            </div>
        </div>

        <!--end::Accordion-->
    </div>
</div>

<!--end::Portlet-->

@section scripts {
    <script>$(function () {
            $("#about-menu-item").addClass("k-menu__item--active");
        });</script>
}

Cloud Apps/Bikefy-Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    City Cycles<br />
    Somewhere, Leeds<br />
    <abbr title="Phone">P:</abbr>
    01611923237
</address>

<address>
    <strong>Queries:</strong> <a href="mailto:citycycles.noreply@gmail.com">citycycles.noreply@gmail.com</a><br />
</address>

@section scripts {
    <script>$(function () {
            $("#contact-menu-item").addClass("k-menu__item--active");
        });</script>
}

Cloud Apps/Bikefy-Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/images/BikeDock.jpg" alt="Bike Docks">
            <div class="carousel-caption d-none d-md-block">
                <h5>Rent a bike from a dock near you</h5>
                @Html.ActionLink("Find nearest dock", "Locations", "Docks", null, new { @class = "btn btn-brand btn-elevate btn-pill" })
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/antiques-bicycle.jpg" alt="Bike">
            <div class="carousel-caption d-none d-md-block">
                <h5>What are you waiting for?</h5>
                @Html.ActionLink("Make a Booking", "MakeBooking", "Bookings", null, new { @class = "btn btn-brand btn-elevate btn-pill" })
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


@section scripts{
    <script>$(function () {
            $("#home-menu-item").addClass("k-menu__item--active");
        });</script>
}

Cloud Apps/Bikefy-Web/Views/Home/Prices.cshtml
@{
    ViewData["Title"] = "Prices";
}

<h2>Prices</h2>