Cloud Apps/Bikefy-Web/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Braintree;
using CityCycles.Composite.BusMessages.Management;
using CityCycles.Composite.Data.ManagementData;
using CityCycles.Composite.Model.Account;
using CityCycles.Composite.Model.Booking;
using CityCycles.Composite.Model.Dock;
using CityCycles.Web.Models;
using CityCycles.Web.Providers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using NServiceBus;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CityCycles.Web.Controllers
{
    [Authorize]
    public class BookingsController : Controller
    {
        public static class LogEvents
        {
            public static readonly EventId MakingBooking = new EventId(7000, nameof(MakeBooking));

        }

        /// <summary>
        /// The logger.
        /// </summary>
        private readonly ILogger _logger;

        /// <summary>
        /// The API provider.
        /// </summary>
        private readonly IApiProvider _apiProvider;

        /// <summary>
        /// The braintree gateway
        /// </summary>
        private readonly IBraintreeGateway _braintree;

        /// <summary>
        /// The endpoint.
        /// </summary>
        private readonly IEndpointInstance _endpoint;

        public BookingsController(IServiceProvider serviceProvider)
        {
            _logger = serviceProvider.GetService<ILogger<BookingsController>>();

            _apiProvider = serviceProvider.GetService<IApiProvider>();
            _braintree = serviceProvider.GetService<IBraintreeGateway>();
            _endpoint = serviceProvider.GetService<IEndpointInstance>();
        }

        [HttpGet]
        public async Task<IActionResult> AllBookings()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> MyBookings()
        {
            var url = _apiProvider.BuildUrl("Booking", $"FindAllUserBookings/{User.FindFirst("nameid").Value}");

            var json = await _apiProvider.SendGetRequest(url);
            var myBookings = JsonConvert.DeserializeObject<List<Booking>>(json);

            var model = new List<ReceiptModel>();

            myBookings.ForEach(b =>
            {
                model.Add(new ReceiptModel()
                {
                    BookingId = b.Id,
                    EndDate = b.EndDate,
                    StartDate = b.StartDate,
                    GrandTotal = b?.Order?.Total.ToString("0.##"),
                    Status = b.Status,
                    TimeTotal = (b.EndDate - b.StartDate).TotalHours.ToString("0.##")
                });
            });

            return View(model);
        }

        [HttpGet("[controller]/[action]/{id}")]
        public async Task<IActionResult> Receipt([FromRoute(Name = "id")]Guid bookingId)
        {
            if (bookingId == Guid.Empty)
                return BadRequest(); // todo, Joe add better error handling

            // Get the booking
            var url = _apiProvider.BuildUrl("Booking", $"FindById/{bookingId}");

            // todo, handle the error
            var json = await _apiProvider.SendGetRequest(url);

            var booking = JsonConvert.DeserializeObject<Booking>(json);


            // Get user profile
            url = _apiProvider.BuildUrl("Auth", $"Profile/{User.FindFirst("nameid").Value}");
            var user = JsonConvert.DeserializeObject<Profile>(await _apiProvider.SendGetRequest(url));

            // Get Pricing
            url = _apiProvider.BuildUrl("Pricing", $"FindById/{booking.PricingId}");
            var pricing = JsonConvert.DeserializeObject<Pricing>(await _apiProvider.SendGetRequest(url));


            // Calculate the times
            var timespan = booking.EndDate - booking.StartDate;
            var timeTotal = Convert.ToDecimal(timespan.TotalHours) * pricing.HourlyPrice;

            // Create hthe model
            var model = new ReceiptModel()
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                TimeTotal = timeTotal.ToString("0.##"),
                BookingId = booking.Id,
                Status = booking.Status,
                StartDate = booking.StartDate,
                Units = timespan.Hours.ToString("0.##"),
                EndDate = booking.EndDate,
                GrandTotal = booking.Order.Total.ToString("0.##"),
                OrderDate = booking.CreatedOn
            };

            // If booking contains booking fee
            if (booking.Order.Items != null && booking.Order.Items.TryGetValue("BookingFee", out var fee))
            {
                model.BookingFee = booking.Order.Items["BookingFee"].ToString("0.##");
            }


            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> MakeBooking()
        {
            // Start request to get access token
            var tokenT = _braintree.ClientToken.GenerateAsync(new ClientTokenRequest
            {
                CustomerId = User.FindFirst("nameid").Value
            });

            try
            {
                // Prepare the bookings model
                var model = await PrepareBookingsModel();

                // await the token from the braintree api
                ViewData["PaymentToken"] = await tokenT;


                // Return the booking mdoel
                return View(model);
            }
            catch (Exception e)
            {
                _logger.LogWarning(LogEvents.MakingBooking, e, "Could not get get docks from API");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MakeBooking(BookingModel request)
        {
            DateTime startDate;
            DateTime endDate;

            try
            {
                // Convert stirng dates to date structure
                startDate = DateTime.ParseExact(request.StartDate, "dd/MM/yyyy HH:mm", CultureInfo.InvariantCulture);
                endDate = DateTime.ParseExact(request.EndDate, "dd/MM/yyyy HH:mm", CultureInfo.InvariantCulture);
            }
            catch (Exception e)
            {
                if (e is ArgumentNullException || e is FormatException)
                {
                    _logger.LogWarning(LogEvents.MakingBooking, e, "Could not convert string dates '{startDate}' and '{endDate}' to Datetime structures", request.StartDate, request.StartDate);
                    BookingModel model = await PrepErroredBookingState();
                    return View(model);
                }

                _logger.LogError(LogEvents.MakingBooking, e, "Could convert date time due to an unexpected exception");

                throw e;
            }

            // validate form
            if (!ModelState.IsValid)
            {
                BookingModel model = await PrepErroredBookingState();

                // Return the booking mdoel
                return View(model);
            }

            var bookingRequest = new BookingRequest()
            {
                DockId = request.DockId,
                StartDate = startDate,
                EndDate = endDate,
                UserId = Guid.Parse(User.FindFirst("nameid").Value)
            };

            var url = _apiProvider.BuildUrl("Booking", "CreateNew");

            // send booking request to api
            var result = await _apiProvider.SendPostRequest(url, bookingRequest);

            // deserialize model to get booking Id
            Dictionary<string, Guid> booking = JsonConvert.DeserializeObject<Dictionary<string, Guid>>(result);

            // If there was an error while reading the dictionary
            if (booking == null || !booking.TryGetValue("BookingId", out var bookingId))
                return RedirectToAction("Error", "Home");

            // If customer wants to pay for the booking now
            if (request.Paynow)
            {
                url = _apiProvider.BuildUrl("Pricing", "Default");

                // Get the default pricing from the api
                var pricing = JsonConvert.DeserializeObject<Pricing>(await _apiProvider.SendGetRequest(url));

                var completeOrder = new ProcessBooking()
                {
                    BookingId = bookingId,
                    CreatedOn = DateTime.UtcNow,
                    PaymentNonce = Request.Form["payment_method_nonce"].FirstOrDefault(),
                    PricingId = pricing.Id
                };

                // Send the message to be processed.
                await _endpoint.Send(completeOrder);
            }

            // take user to their bookings page
            return RedirectToAction(nameof(MyBookings));
        }

        [HttpGet("[controller]/[action]/{id}")]
        public async Task<IActionResult> RetryPayment([FromRoute(Name = "id")]Guid bookingId)
        {
            // Get the booking
            var url = _apiProvider.BuildUrl("Booking", $"FindById/{bookingId}");

            // todo, handle the error
            var booking = JsonConvert.DeserializeObject<Booking>(await _apiProvider.SendGetRequest(url));


            url = _apiProvider.BuildUrl("Pricing", "Default");

            // Get the default pricing from the api
            var pricing = JsonConvert.DeserializeObject<Pricing>(await _apiProvider.SendGetRequest(url));


            var completeOrder = new ProcessBooking()
            {
                BookingId = bookingId,
                CreatedOn = DateTime.UtcNow,
                PricingId = pricing.Id
            };

            // Send payment to be retried
            await _endpoint.Send(completeOrder);

Cloud Apps/Bikefy-Web/Views/Bookings/MakeBooking.cshtml
@model CityCycles.Web.Models.BookingModel

<input type="hidden" id="Payment-Token" value="@ViewData["PaymentToken"]" />

<!--being:: Form -->
<form autocomplete="off" method="post" class="k-form" asp-action="MakeBooking" asp-antiforgery="true">
    <!--begin::Portlet-->
    <div class="k-portlet" id="k_portlet">
        <div class="k-portlet__head k-portlet__head--lg">
            <div class="k-portlet__head-label">
                <spa class="k-portlet__head-icon">
                    <i class="flaticon-time-3"></i>
                </spa>
                <h3 class="k-portlet__head-title">
                    Booking
                </h3>
            </div>
            <div class="k-portlet__head-toolbar">
                <div class="k-portlet__head-group">
                </div>
            </div>
        </div>
        <div class="k-portlet__body">
            @* The start and end dates to be sent to backend*@

            <div class="form-group row">
                <div class="col-lg-6">
                    <label>Select a dock. </label>
                    @Html.DropDownList("DockId", null, "Select Dock", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(s => s.DockId, "", new { @class = "text-danger" })
                </div>

                <div class="col-lg-6">
                    <label>Select a date ranage.</label>
                    <div class="row form-group">
                        <div class="col-md-6">
                            <div class="input-group date">
                                <input type="text" asp-for="StartDate" id="startDateId" class="form-control booking-datepicker" placeholder="Select date &amp; time">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="flaticon-calendar-with-a-clock-time-tools"></i></span>
                                </div>
                            </div>
                            @Html.ValidationMessageFor(s => s.StartDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            <div class="input-group date">
                                <input type="text" asp-for="EndDate" id="endDateId" class="form-control booking-datepicker" placeholder="Select end date &amp; time">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="flaticon-calendar-with-a-clock-time-tools"></i></span>
                                </div>
                            </div>
                            @Html.ValidationMessageFor(s => s.EndDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-6">
                    <div class="k-portlet k-portlet--height-fluid">
                        <div class="k-portlet__head">
                            <div class="k-portlet__head-label">
                                <h3 class="k-portlet__head-title">Total Booking</h3>
                            </div>
                        </div>
                        <div class="k-portlet__body">
                            <table class="checkout__summary">
                                <thead>
                                    <tr>
                                        <th>Item</th>
                                        <th>Quantity</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Booking Fee</td>
                                        <td>1</td>
                                        <td>£ @(Model.Pricing.BookingFee.ToString("0.##"))</td>
                                    </tr>
                                    <tr>
                                        <td>Booking Time</td>
                                        <td id="bookingTime"></td>
                                        <td id="bookingTimeCost"></td>
                                    </tr>
                                    <tr>
                                        <td><b>GRAND TOTAL:</b></td>
                                        <td></td>
                                        <td id="finalTotal"></td>
                                    </tr>
                                </tbody>
                            </table>
                            <p>*Note that additional fees may be charged if the bike is not returned on time</p>
                        </div>
                    </div>
                </div>

                <div id="payment-form" class="col-md-6">

                </div>
            </div>

            <!--end: Form-->
        </div>
        <div class="k-portlet__foot">
            <div class="k-form__actions k-form__actions">
                <div class="form-group row col-md-6">
                    <label class="col-3 col-form-label">Pay Now</label>
                    <div class="col-3">
                        <span class="k-switch k-switch--success">
                            <label>
                                <input asp-for="Paynow">
                                <span></span>
                            </label>
                        </span>
                    </div>
                    <div class="col-md-3">
                        <button type="submit" class="btn btn-brand">Place Book</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section scripts {
    <script>
    $(function () {
            $("#bookings-menu-item").addClass("k-menu__item--open k-menu__item--here");
            $("#bookings-menu-item-makebooking").addClass("k-menu__item--active");
        });</script>

    <script>
        // Contains the pricing model
        let pricing = @(Json.Serialize(Model.Pricing));
    </script>

    <script src="https://js.braintreegateway.com/js/braintree-2.32.1.min.js" asp-append-version="true"></script>
    <script src="~/js/bookings-create.js"></script>
}

Cloud Apps/Bikefy-Web/Views/Bookings/MyBookings.cshtml
@model List<CityCycles.Web.Models.ReceiptModel>
@using CityCycles.Composite.Data.ManagementData

@{
    ViewData["Title"] = "Your Bookings";
}

<div class="k-portlet k-portlet--mobile">
    <div class="k-portlet__head">
        <div class="k-portlet__head-label">
            <h3 class="k-portlet__head-title">
                Bookings
            </h3>
        </div>
    </div>

    <div class="k-portlet__body">

        <!--begin: Datatable -->
        <div id="k_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row">
                <div class="col-12">
                    @{
                        if (!ViewData.ModelState.IsValid)
                        {

                            @:<div class="alert alert-danger">
                                @:<div class="alert-icon">
                                    @: <i class="flaticon-warning"></i>
                                @: </div>
                                @:<div class="alert-text">
                                    @Html.ValidationMessage("Custom-Error")
                                @: </div>
                            @: </div>
                        }
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="dataTables_scroll">
                        <div class="dataTables_scrollBody"
                             style="position: relative; overflow: auto; width: 100%; max-height: 50vh;">
                            <table class="table table-striped- table-bordered table-hover table-checkable dataTable no-footer"
                                   id="k_table_1" role="grid" aria-describedby="k_table_1_info">
                                <thead>
                                    <tr role="row">
                                        <th aria-controls="k_table_1" rowspan="1" colspan="1">
                                            <div class="dataTables_sizing">
                                                Booking ID
                                            </div>
                                        </th>
                                        <th aria-controls="k_table_1" rowspan="1" colspan="1">
                                            <div class="dataTables_sizing">
                                                Start date
                                            </div>
                                        </th>
                                        <th aria-controls="k_table_1" rowspan="1" colspan="1">
                                            <div class="dataTables_sizing">
                                                End date
                                            </div>
                                        </th>
                                        <th aria-controls="k_table_1" rowspan="1" colspan="1">
                                            <div class="dataTables_sizing">
                                                Status
                                            </div>
                                        </th>
                                        <th aria-controls="k_table_1" rowspan="1" colspan="1">
                                            <div class="dataTables_sizing">
                                                Time
                                            </div>
                                        </th>
                                        <th aria-controls="k_table_1" rowspan="1" colspan="1">
                                            <div class="dataTables_sizing">
                                                Cost
                                            </div>
                                        </th>
                                        <th rowspan="1" colspan="1">

                                        </th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (var booking in Model)
                                    {
                                        <tr role="row" class="odd">
                                            <td>
                                                @(booking.BookingId)
                                            </td>
                                            <td>
                                                @(booking.StartDate)
                                            </td>
                                            <td>
                                                @(booking.EndDate)
                                            </td>
                                            <td>
                                                @{
                                                    switch (booking.Status)
                                                    {
                                                        case CityCycles.Composite.Data.ManagementData.BookingStatus.Processed:
                                                            {
                                                                @:<span class="badge badge-pill badge-primary">Processed</span>
                                                                break;
                                                            }
                                                        case CityCycles.Composite.Data.ManagementData.BookingStatus.Accepted:
                                                            {
                                                                @:<span class="badge badge-pill badge-success">Accepted</span>
                                                                break;
                                                            }
                                                        case CityCycles.Composite.Data.ManagementData.BookingStatus.Declined:
                                                            {
                                                                @:<span class="badge badge-pill badge-danger">Declined</span>
                                                                break;
                                                            }
                                                        default:
                                                            {
                                                                @:<span class="badge badge-pill badge-secondary">@booking.Status ...</span>
                                                                break;
                                                            }
                                                    }
                                                }
                                            </td>
                                            <td>
                                                @{

                                                    @:@booking.TimeTotal Hours
                                                }

                                            </td>
                                            <td>
                                                @{
                                                    if (booking.Status == BookingStatus.Accepted)
                                                    {
                                                        @:£@(booking.GrandTotal)
                                                    }
                                                }
                                            </td>
                                            <td>
                                                @{
                                                    if (booking.Status == BookingStatus.Accepted)
                                                    {
                                                        <a asp-controller="Bookings" asp-action="Receipt" asp-route-id="@booking.BookingId" class="btn btn-link ">
                                                            <span class="odd">View Receipt</span>
                                                        </a>
                                                    }
                                                    else if (booking.Status == BookingStatus.Declined)
                                                    {
                                                        <a asp-controller="Bookings" asp-action="RetryPayment" asp-route-id="@booking.BookingId" class="btn btn-warning btn-sm">
                                                            <i></i>
                                                            <span class="odd">Retry payment</span>
                                                        </a>
                                                    }
                                                }
                                            </td>
                                        </tr>
                                    }
                                </tbody>


                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--end: Datatable -->
    </div>
</div>

@section scripts {
    <script>$(function () {
            $("#bookings-menu-item").addClass("k-menu__item--open k-menu__item--here");
            $("#bookings-menu-item-update").addClass("k-menu__item--active");
        });</script>
}

Cloud Apps/Bikefy-Web/Views/Bookings/Receipt.cshtml
@model CityCycles.Web.Models.ReceiptModel
@{
    ViewData["Title"] = "Receipt";
}

<div class="k-portlet">
    <div class="k-invoice-v2">
        <div class="k-invoice-v2__header">
            <div class="k-invoice-v2__header-left">
                <h1 class="k-invoice-v2__title">RECEIPT</h1>
            </div>
            <div class="k-invoice-v2__header-right">
                <div class="k-invoice-v2__companyinfo">
                    City Cycles
                </div>
            </div>
        </div>
        <div class="k-invoice-v2__line"></div>
        <div class="k-invoice-v2__details">
            <div class="k-invoice-v2__details-left">
                <div class="k-invoice-v2__details-label">INVOICE TO:</div>
                <div class="k-invoice-v2__details-value">
                    @(Model.FirstName) @(Model.LastName) 
                </div>
            </div>
            <div class="k-invoice-v2__details-right">
                <div class="k-invoice-v2__detail--date">
                    <div class="k-invoice-v2__details-label">START DATE:</div>
                    <div class="k-invoice-v2__details-value">@(Model.StartDate)</div>
                </div>
                <div class="k-invoice-v2__detail--date">
                    <div class="k-invoice-v2__details-label">END DATE:</div>
                    <div class="k-invoice-v2__details-value">@(Model.EndDate)</div>
                </div>
                <div class="k-invoice-v2__details--invoiceno">
                    <div class="k-invoice-v2__details-label">BOOKING ID:</div>
                    <div class="k-invoice-v2__details-value">@(Model.BookingId)</div>
                </div>
            </div>
        </div>
        <div class="k-invoice-v2__body">
            <div class="table-responsive">
                <table class="k-invoice-v2__summary">
                    <thead class="k-invoice-v2__summary-header">
                        <tr>
                            <th>Item</th>
                            <th>Quantity</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody class="k-invoice-v2__summary-body">
                        <tr>
                            <td>Booking Fee</td>
                            <td>1</td>
                            <td>£ @(Model.BookingFee)</td>
                        </tr>
                        <tr>
                            <td>Booking Time</td>
                            <td>@(Model.Units)</td>
                            <td>£ @(Model.TimeTotal)</td>
                        </tr>
                        <tr>
                            <td><pre>     </pre></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><pre>     </pre></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td class="strong"><b>Amount Charged</b></td>
                            <td></td>
                            <td><b>£@Model.GrandTotal</b></td>
                        </tr>

                    </tbody>
                </table>
            </div>


            
        </div>
    </div>
</div>